### ISSUE TITLE
I don't think its working for Windows?

### ISSUE THREAD

**Issue by Kayizoku** [MineBill/mpv-history#2]
I added this to my scripts folder but it sadly didn't work. Will it only work for Linux? If so, could you tell me how I can make it work for Windows too? I would appreciate it as it's a really unique and cool script I would like to add to my arsenal and it's very useful.

**Comment by MineBill** [comment]
Hello! If you could find some logs and post them here it would help but i'll take a look anyway and see what could be the problem first thing in the morning!

**Comment by Kayizoku** [comment]
Sure thing, I appreciate the swift reply. I attached my log down below. Sleep well :)


[output.txt](https://github.com/MineBill/mpv-history/files/7804316/output.txt)

**Comment by MineBill** [comment]
I've been trying to get this to work on windows for hours. I've update the script to be platform-agnostic when loading the database file but the problem is installing the lsqlite3 library on windows. `lsqlite3` assumes there is already an sqlite3 installation so the problem becomes how to do that. I've tried `lsqlite3complete` which downloads and install sqlite3 but it only works for linux. You could manually compile the library but that would require figuring out how and where to place what file so they can be found at runtime(which i also tried with msvc and mingw). It's a mess. I'm sorry i couldn't  figure it out.

**Comment by Kayizoku** [comment]
> I've been trying to get this to work on windows for hours. I've update the script to be platform-agnostic when loading the database file but the problem is installing the lsqlite3 library on windows. `lsqlite3` assumes there is already an sqlite3 installation so the problem becomes how to do that. I've tried `lsqlite3complete` which downloads and install sqlite3 but it only works for linux. You could manually compile the library but that would require figuring out how and where to place what file so they can be found at runtime(which i also tried with msvc and mingw). It's a mess. I'm sorry i couldn't figure it out.

same, I was unable to get it work as well. Oh well, at least we made some progress. That's nice. Hopefully, we'll find a way eventually. Thank you anyways for you help. I much appreciate that
